### PR TITLE
Suggested tweaks

### PR DESCRIPTION
**Pull request by AdamGAmar**
@beschizza I appreciate the amount of effort you've put in here :) Suggested a few changes - apologies for any whitespace that got shuffled in the process! Feel free to use any or all of the commits you'd like.

- Fixed up some HTML syntax that was making my code editor complain. (mostly just adding a closing `html` tag and closing the button tags)
- The negative stat bug (when I experienced it) was caused by a JS error stopping code execution when a job's quest story couldn't be found (ie, the job titles didn't match, mostly for the `Lord`s).
- Replaced `new Array()` with `[]` for consistency.
- Used constant arrays to help iterate over stats and experience, which cleans up the code a fair bit.

I didn't make the change since there were a lot of jobs (so many jobs) but I would also suggest a few changes to job code:
1) moving the `storyFlavor` items into the job,
2) moving the job requirement into the job (so that you can just loop over all jobs to find which one you meet the requirements for), and
3) changing the "YES" code to a function, i.e. `accept` (you'd then keep track of which job was being offered and call that function).

So your job would look like this:

```
var storyLordEngineer = { //xxx
	played: 0,
	title: "Lord Engineer",
	picture: "images/story1.png",
	text: "In wartime, the Lord Engineer devises the most cunning and spectacular weapons of war. In peacetime, more efficient sewer systems. It's peacetime, but maybe you could do something about that, if only you took the job.",
	meetsRequirements: function() { return character.STR + character.DEX + character.INT > 52 },
	accept: function() { character.job='Engineer' },
	hobbies: [ 'Spending the kingdom\'s cash on mad machines','causing mysterious explosions','draining the actual swamp' ]
}
```

### CODE REVIEW

**Comment by beschizza** [comment]
Awesome! It's late here, will hit this first thing in the morning

**Comment by beschizza** [comment]
This is great! I'm learning a lot about how to improve my own code from these contributions.

One thing: character.highestStat never changes now that you've refined that object -- the result being that you never get the original early job offers that depend on it being updated from the effective default (CHA) set at the outset. 

ie CHA is set as the higheststat at the outset and never changes, which means the only "starting" job you'll get offered is the CHA one, "stagehand" assuming you pump some points to get it to the other requirement

I think I can tackle it myself but if you'd like to please be my guest :)

**Comment by beschizza** [comment]
I think I got it.

**Comment by AdamGAmar** [comment]
@beschizza Great! Sorry about that bug, there's always one... The `this` scope in JS always gets me. It doesn't work inside the called function, so an alternative fix would have been to use everyone's favourite syntax `var _this = this;` at the start of the function and reference `_this` instead.

Apologies again, and glad to hear it's been helpful :)

**Pull request merged**
